version: '3.8'
services:
  dev-db:
    image: postgres:14.9
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: jay
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cdrrmo
    networks:
      - cdrrmo
  test-db:
    image: postgres:14.9
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: jay
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cdrrmo
    networks:
      - cdrrmo
networks:
  cdrrmo: